name: Release 3X-UI for Docker
on:
  workflow_dispatch:
  push:
    tags:
      - "s*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
   
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          samssh1/3x-ui
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=pep440,pattern={{version}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}